export default images = {
    "aircraft carrier":require('./quickdraw/aircraftcarrier.jpg'),
    "airplane":require('./quickdraw/airplane.jpg'),
    "alarm clock":require('./quickdraw/alarmclock.jpg'),
    "ambulance":require('./quickdraw/ambulance.jpg'),
    "angel":require('./quickdraw/angel.jpg'),
    "animal migration":require('./quickdraw/animalmigration.jpg'),
    "ant":require('./quickdraw/ant.jpg'),
    "anvil":require('./quickdraw/anvil.jpg'),
    "apple":require('./quickdraw/apple.jpg'),
    "arm":require('./quickdraw/arm.jpg'),
    "asparagus":require('./quickdraw/asparagus.jpg'),
    "axe":require('./quickdraw/axe.jpg'),
    "bagpack":require('./quickdraw/bagpack.jpg'),
    "banana":require('./quickdraw/banana.jpg'),
    "bandage":require('./quickdraw/bandage.jpg'),
    "barn":require('./quickdraw/barn.jpg'),
    "baseball":require('./quickdraw/baseball.jpg'),
    "baseball bat":require('./quickdraw/baseballbat.jpg'),
    "basket":require('./quickdraw/basket.jpg'),
    "basketball":require('./quickdraw/basketball.jpg'),
    "bat":require('./quickdraw/bat.jpg'),
    "bathtub":require('./quickdraw/bathtub.jpg'),
    "beach":require('./quickdraw/beach.jpg'),
    "bear":require('./quickdraw/bear.jpg'),
    "beard":require('./quickdraw/beard.jpg'),
    "bed":require('./quickdraw/bed.jpg'),
    "bee":require('./quickdraw/bee.jpg'),
    "belt":require('./quickdraw/belt.jpg'),
    "bench":require('./quickdraw/bench.jpg'),
    "bicycle":require('./quickdraw/bicycle.jpg'),
    "binoculars":require('./quickdraw/binoculars.jpg'),
    "bird":require('./quickdraw/bird.jpg'),
    "birthday cake":require('./quickdraw/birthdaycake.jpg'),
    "blackberry":require('./quickdraw/blackberry.jpg'),
    "blueberry":require('./quickdraw/blueberry.jpg'),
    "book":require('./quickdraw/book.jpg'),
    "boomerang":require('./quickdraw/boomerang.jpg'),
    "bottlecap":require('./quickdraw/bottlecap.jpg'),
    "bowtie":require('./quickdraw/bowtie.jpg'),
    "bracelet":require('./quickdraw/bracelet.jpg'),
    "brain":require('./quickdraw/brain.jpg'),
    "bread":require('./quickdraw/bread.jpg'),
    "bridge":require('./quickdraw/bridge.jpg'),
    "broccoli":require('./quickdraw/broccoli.jpg'),
    "broom":require('./quickdraw/broom.jpg'),
    "bucket":require('./quickdraw/bucket.jpg'),
    "bulldozer":require('./quickdraw/bulldozer.jpg'),
    "bus":require('./quickdraw/bus.jpg'),
    "bush":require('./quickdraw/bush.jpg'),
    "butterfly":require('./quickdraw/butterfly.jpg'),
    "cactus":require('./quickdraw/cactus.jpg'),
    "cake":require('./quickdraw/cake.jpg'),
    "calculator":require('./quickdraw/calculator.jpg'),
    "calendar":require('./quickdraw/calendar.jpg'),
    "camel":require('./quickdraw/camel.jpg'),
    "camera":require('./quickdraw/camel.jpg'),
    "camouflage":require('./quickdraw/camouflage.jpg'),
    "campfire":require('./quickdraw/campfire.jpg'),
    "candle":require('./quickdraw/candle.jpg'),
    "cannon":require('./quickdraw/cannon.jpg'),
    "canoe":require('./quickdraw/canoe.jpg'),
    "car":require('./quickdraw/car.jpg'),
    "carrot":require('./quickdraw/carrot.jpg'),
    "castle":require('./quickdraw/castle.jpg'),
    "cat":require('./quickdraw/cat.jpg'),
    "ceiling fan":require('./quickdraw/ceilingfan.jpg'),
    "cello phone":require('./quickdraw/cellphone.jpg'),
    "cello":require('./quickdraw/cello.jpg'),
    "chair":require('./quickdraw/chair.jpg'),
    "chandelier":require('./quickdraw/chandelier.jpg'),
    "church":require('./quickdraw/church.jpg'),
    "circle": require('./quickdraw/circle.jpg'),
    "clarinet":require('./quickdraw/clarinet.jpg'),
    "clock":require('./quickdraw/clock.jpg'),
    "cloud":require('./quickdraw/cloud.jpg'),
    "coffee cup":require('./quickdraw/coffeecup.jpg'),
    "compass":require('./quickdraw/compass.jpg'),
    "computer":require('./quickdraw/computer.jpg'),
    "cookie":require('./quickdraw/cookie.jpg'),
    "cooler":require('./quickdraw/cooler.jpg'),
    "couch":require('./quickdraw/couch.jpg'),
    "cow":require('./quickdraw/cow.jpg'),
    "crab":require('./quickdraw/crab.jpg'),
    "crayon":require('./quickdraw/crayon.jpg'),
    "crocodile":require('./quickdraw/crocodile.jpg'),
    "crown":require('./quickdraw/crown.jpg'),
    "cruise ship":require('./quickdraw/cruiseship.jpg'),
    "cup":require('./quickdraw/cup.jpg'),
    "diamond":require('./quickdraw/diamond.jpg'),
    "dishwasher":require('./quickdraw/dishwasher.jpg'),
    "diving board":require('./quickdraw/divingboard.jpg'),
    "dog":require('./quickdraw/dog.jpg'),
    "dolphin":require('./quickdraw/dolphin.jpg'),
    "donut":require('./quickdraw/donut.jpg'),
    "door":require('./quickdraw/door.jpg'),
    "dragon":require('./quickdraw/dragon.jpg'),
    "dresser":require('./quickdraw/dresser.jpg'),
    "drill":require('./quickdraw/drill.jpg'),
    "drums":require('./quickdraw/drums.jpg'),
    "duck":require('./quickdraw/duck.jpg'),
    "dumbbell":require('./quickdraw/dumbbell.jpg'),
    "ear":require('./quickdraw/ear.jpg'),
    "elbow":require('./quickdraw/elbow.jpg'),
    "elephant":require('./quickdraw/elephant.jpg'),
    "envelop":require('./quickdraw/envelop.jpg'),
    "eraser":require('./quickdraw/eraser.jpg'),
    "eye":require('./quickdraw/eye.jpg'),
    "eyeglasses":require('./quickdraw/eyeglasses.jpg'),
    "face":require('./quickdraw/face.jpg'),
    "fan":require('./quickdraw/fan.jpg'),
    "feather":require('./quickdraw/feather.jpg'),
    "fence":require('./quickdraw/fence.jpg'),
    "finger":require('./quickdraw/finger.jpg'),
    "fire hydrant":require('./quickdraw/firehydrant.jpg'),
    "fireplace":require('./quickdraw/fireplace.jpg'),
    "firetruck":require('./quickdraw/firetruck.jpg'),
    "fish":require('./quickdraw/fish.jpg'),
    "flamingo":require('./quickdraw/flamingo.jpg'),
    "flashlight":require('./quickdraw/flashlight.jpg'),
    "flip flop":require('./quickdraw/flipflops.jpg'),
    "floor lamp":require('./quickdraw/floorlamp.jpg'),
    "flower":require('./quickdraw/flower.jpg'),
    "flying saucer":require('./quickdraw/flyingsaucer.jpg'),
    "foot":require('./quickdraw/foot.jpg'),
    "fork":require('./quickdraw/fork.jpg'),
    "frog":require('./quickdraw/frog.jpg'),
    "frying pan":require('./quickdraw/fryingpan.jpg'),
    "garden":require('./quickdraw/garden.jpg'),
    "garden hose":require('./quickdraw/gardenhose.jpg'),
    "girraffe":require('./quickdraw/giraffe.jpg'),
    "goatee":require('./quickdraw/goatee.jpg'),
    "golf club":require('./quickdraw/golfclub.jpg'),
    "grapes":require('./quickdraw/grapes.jpg'),
    "grass":require('./quickdraw/grass.jpg'),
    "guitar":require('./quickdraw/guitar.jpg'),
    "hamburger":require('./quickdraw/hamburger.jpg'),
    "hammer":require('./quickdraw/hammer.jpg'),
    "hand":require('./quickdraw/hand.jpg'),
    "harp":require('./quickdraw/harp.jpg'),
    "hat":require('./quickdraw/hat.jpg'),
    "headphone":require('./quickdraw/headphones.jpg'),
    "hedgehog":require('./quickdraw/hedgehog.jpg'),
    "helicopter":require('./quickdraw/helicopter.jpg'),
    "helmet":require('./quickdraw/helmet.jpg'),
    "hexagon":require('./quickdraw/hexagon.jpg'),
    "hockey puck":require('./quickdraw/hockeypuck.jpg'),
    "hockey stick":require('./quickdraw/hockeystick.jpg'),
    "horse":require('./quickdraw/horse.jpg'),
    "hospital":require('./quickdraw/hospital.jpg'),
    "hot air balloon":require('./quickdraw/hotairballoon.jpg'),
    "hot dog":require('./quickdraw/hotdog.jpg'),
    "hot tub":require('./quickdraw/hottub.jpg'),
    "hourglass":require('./quickdraw/hourglass.jpg'),
    "house":require('./quickdraw/house.jpg'),
    "house plant":require('./quickdraw/houseplant.jpg'),
    "hurricane":require('./quickdraw/hurricane.jpg'),
    "ice cream":require('./quickdraw/icecream.jpg'),
    "jacket":require('./quickdraw/jacket.jpg'),
    "jail":require('./quickdraw/jail.jpg'),
    "kangaroo":require('./quickdraw/kangaroo.jpg'),
    "key":require('./quickdraw/key.jpg'),
    "keyboard":require('./quickdraw/keyboard.jpg'),
    "knee":require('./quickdraw/knee.jpg'),
    "knife":require('./quickdraw/knife.jpg'),
    "ladder":require('./quickdraw/ladder.jpg'),
    "lantern":require('./quickdraw/lantern.jpg'),
    "laptop":require('./quickdraw/laptop.jpg'),
    "leaf":require('./quickdraw/leaf.jpg'),
    "leg":require('./quickdraw/leg.jpg'),
    "light bulb":require('./quickdraw/lightbulb.jpg'),
    "lighter":require('./quickdraw/lighter.jpg'),
    "light house":require('./quickdraw/lighthouse.jpg'),
    "lightning":require('./quickdraw/lightning.jpg'),
    "line":require('./quickdraw/line.jpg'),
    "lion":require('./quickdraw/lion.jpg'),
    "lipstick":require('./quickdraw/lipstick.jpg'),
    "lobster":require('./quickdraw/lobster.jpg'),
    "lollipop":require('./quickdraw/lollipop.jpg'),
    "mailbox":require('./quickdraw/mailbox.jpg'),
    "map":require('./quickdraw/map.jpg'),
    "marker":require('./quickdraw/marker.jpg'),
    "matches":require('./quickdraw/matches.jpg'),
    "megaphone":require('./quickdraw/megaphone.jpg'),
    "mermaid":require('./quickdraw/mermaid.jpg'),
    "microphone":require('./quickdraw/microphone.jpg'),
    "microwave":require('./quickdraw/microwave.jpg'),
    "monkey":require('./quickdraw/monkey.jpg'),
    "moon":require('./quickdraw/moon.jpg'),
    "mosquito":require('./quickdraw/mosquito.jpg'),
    "motorbike":require('./quickdraw/motorbike.jpg'),
    "mountain":require('./quickdraw/mountain.jpg'),
    "mouse":require('./quickdraw/mouse.jpg'),
    "moustache":require('./quickdraw/moustache.jpg'),
    "mouth":require('./quickdraw/mouth.jpg'),
    "mug":require('./quickdraw/mug.jpg'),
    "mushroom":require('./quickdraw/mushroom.jpg'),
    "nail":require('./quickdraw/nail.jpg'),
    "necklace":require('./quickdraw/necklace.jpg'),
    "nose":require('./quickdraw/nose.jpg'),
    "ocean":require('./quickdraw/ocean.jpg'),
    "octagon":require('./quickdraw/octagon.jpg'),
    "octopus":require('./quickdraw/octopus.jpg'),
    "onion":require('./quickdraw/onion.jpg'),
    "oven":require('./quickdraw/oven.jpg'),
    "owl":require('./quickdraw/owl.jpg'),
    "paintbrush":require('./quickdraw/paintbrush.jpg'),
    "paint can":require('./quickdraw/paintcan.jpg'),
    "palm tree":require('./quickdraw/palmtree.jpg'),
    "panda":require('./quickdraw/panda.jpg'),
    "pants":require('./quickdraw/pants.jpg'),
    "paper clip":require('./quickdraw/paperclip.jpg'),
    "parachute":require('./quickdraw/parachute.jpg'),
    "parrot":require('./quickdraw/parrot.jpg'),
    "passport":require('./quickdraw/passport.jpg'),
    "peanut":require('./quickdraw/peanut.jpg'),
    "pear":require('./quickdraw/pear.jpg'),
    "peas":require('./quickdraw/peas.jpg'),
    "pencil":require('./quickdraw/pencil.jpg'),
    "penguin":require('./quickdraw/penguin.jpg'),
    "piano":require('./quickdraw/piano.jpg'),
    "pickup truck":require('./quickdraw/pickuptruck.jpg'),
    "picture frame":require('./quickdraw/pictureframe.jpg'),
    "pig":require('./quickdraw/pig.jpg'),
    "pillow":require('./quickdraw/pillow.jpg'),
    "pineapple":require('./quickdraw/pineapple.jpg'),
    "pizza":require('./quickdraw/pizza.jpg'),
    "pliers":require('./quickdraw/pliers.jpg'),
    "police car":require('./quickdraw/policecar.jpg'),
    "pond":require('./quickdraw/pond.jpg'),
    "pool":require('./quickdraw/pool.jpg'),
    "popsicle":require('./quickdraw/popsicle.jpg'),
    "postcard":require('./quickdraw/postcard.jpg'),
    "potato":require('./quickdraw/potato.jpg'),
    "power outlet":require('./quickdraw/poweroutlet.jpg'),
    "purse":require('./quickdraw/purse.jpg'),
    "rabbit":require('./quickdraw/rabbit.jpg'),
    "raccon":require('./quickdraw/raccon.jpg'),
    "radio":require('./quickdraw/radio.jpg'),
    "rain":require('./quickdraw/rain.jpg'),
    "rainbow":require('./quickdraw/rainbow.jpg'),
    "rake":require('./quickdraw/rake.jpg'),
    "remote control":require('./quickdraw/remotecontrol.jpg'),
    "rhinoceros":require('./quickdraw/rhinoceros.jpg'),
    "rifle":require('./quickdraw/rifle.jpg'),
    "river":require('./quickdraw/river.jpg'),
    "roller coaster":require('./quickdraw/rollercoaster.jpg'),
    "rollerskate":require('./quickdraw/rollerskater.jpg'),
    "sailboat":require('./quickdraw/sailboat.jpg'),
    "sandwich":require('./quickdraw/sandwich.jpg'),
    "saw":require('./quickdraw/saw.jpg'),
    "saxophone":require('./quickdraw/saxophone.jpg'),
    "school bus":require('./quickdraw/schoolbus.jpg'),
    "scissors":require('./quickdraw/scissors.jpg'),
    "scorpion":require('./quickdraw/scorpion.jpg'),
    "screwdriver":require('./quickdraw/screwdriver.jpg'),
    "sea turtle":require('./quickdraw/seaturtle.jpg'),
    "see saw":require('./quickdraw/seesaw.jpg'),
    "shark":require('./quickdraw/shark.jpg'),
    "sheep":require('./quickdraw/sheep.jpg'),
    "shoe":require('./quickdraw/shoe.jpg'),
    "shorts":require('./quickdraw/shorts.jpg'),
    "shovel":require('./quickdraw/shovel.jpg'),
    "sink":require('./quickdraw/sink.jpg'),
    "skateboard":require('./quickdraw/skateboard.jpg'),
    "skull":require('./quickdraw/skull.jpg'),
    "skycraper":require('./quickdraw/skycraper.jpg'),
    "sleeping bag":require('./quickdraw/sleepingbag.jpg'),
    "smiley face":require('./quickdraw/smileyface.jpg'),
    "snail":require('./quickdraw/snail.jpg'),
    "snake":require('./quickdraw/snake.jpg'),
    "snorkel":require('./quickdraw/snorkel.jpg'),
    "snowflake":require('./quickdraw/snowflake.jpg'),
    "snowman":require('./quickdraw/snowman.jpg'),
    "soccer ball":require('./quickdraw/soccerball.jpg'),
    "sock":require('./quickdraw/sock.jpg'),
    "speedboat":require('./quickdraw/speedboat.jpg'),
    "spider":require('./quickdraw/spider.jpg'),
    "spoon":require('./quickdraw/spoon.jpg'),
    "spreadsheet":require('./quickdraw/spreadsheet.jpg'),
    "square":require('./quickdraw/square.jpg'),
    "squiggle":require('./quickdraw/squiggle.jpg'),
    "squirrel":require('./quickdraw/squirrel.jpg'),
    "stair":require('./quickdraw/stairs.jpg'),
    "star":require('./quickdraw/star.jpg'),
    "steak":require('./quickdraw/steak.jpg'),
    "stereo":require('./quickdraw/stereo.jpg'),
    "stethoscope":require('./quickdraw/stethoscope.jpg'),
    "stitches":require('./quickdraw/stitches.jpg'),
    "stop sign":require('./quickdraw/stopsign.jpg'),
    "stove":require('./quickdraw/stove.jpg'),
    "strawberry":require('./quickdraw/strawberry.jpg'),
    "streetlight":require('./quickdraw/streetlight.jpg'),
    "string bean":require('./quickdraw/stringbean.jpg'),
    "submarine":require('./quickdraw/submarine.jpg'),
    "suitcase":require('./quickdraw/suitcase.jpg'),
    "sun":require('./quickdraw/sun.jpg'),
    "swan":require('./quickdraw/swan.jpg'),
    "sweater":require('./quickdraw/sweater.jpg'),
    "swing set":require('./quickdraw/swingset.jpg'),
    "sword":require('./quickdraw/sword.jpg'),
    "syringe":require('./quickdraw/syringe.jpg'),
    "t shirt":require('./quickdraw/tshirt.jpg'),
    "table":require('./quickdraw/table.jpg'),
    "teapot":require('./quickdraw/teapot.jpg'),
    "teddy bear":require('./quickdraw/teddybear.jpg'),
    "telephone":require('./quickdraw/telephone.jpg'),
    "television":require('./quickdraw/television.jpg'),
    "tennis racquet":require('./quickdraw/tennisracquet.jpg'),
    "tent":require('./quickdraw/tent.jpg'),
    "the eiffel tower":require('./quickdraw/TheEiffelTower.jpg'),
    "the great wall of china":require('./quickdraw/TheGreatWallofChina.jpg'),
    "the mona lisa":require('./quickdraw/Themonalisa.jpg'),
    "tiger":require('./quickdraw/tiger.jpg'),
    "toaster":require('./quickdraw/toaster.jpg'),
    "toe":require('./quickdraw/toe.jpg'),
    "toilet":require('./quickdraw/toilet.jpg'),
    "tooth":require('./quickdraw/tooth.jpg'),
    "toothbrush":require('./quickdraw/toothbrush.jpg'),
    "toothpaste":require('./quickdraw/toothpaste.jpg'),
    "tornado":require('./quickdraw/tornado.jpg'),
    "tractor":require('./quickdraw/tractor.jpg'),
    "traffic light":require('./quickdraw/trafficlight.jpg'),
    "train":require('./quickdraw/train.jpg'),
    "tree":require('./quickdraw/tree.jpg'),
    "triangle":require('./quickdraw/triangle.jpg'),
    "trombone":require('./quickdraw/trombone.jpg'),
    "truck":require('./quickdraw/truck.jpg'),
    "trumpet":require('./quickdraw/trumpet.jpg'),
    "umbrella":require('./quickdraw/umbrella.jpg'),
    "underwear":require('./quickdraw/underwear.jpg'),
    "van":require('./quickdraw/van.jpg'),
    "vase":require('./quickdraw/vase.jpg'),
    "violin":require('./quickdraw/violin.jpg'),
    "washing machine":require('./quickdraw/washingmachine.jpg'),
    "watermelon":require('./quickdraw/watermelon.jpg'),
    "waterslide":require('./quickdraw/waterslide.jpg'),
    "whale":require('./quickdraw/whale.jpg'),
    "wheel":require('./quickdraw/wheel.jpg'),
    "windmill":require('./quickdraw/windmill.jpg'),
    "winebottle":require('./quickdraw/winebottle.jpg'),
    "wineglass":require('./quickdraw/wineglass.jpg'),
    "wristwatch":require('./quickdraw/wristwatch.jpg'),
    "yoga":require('./quickdraw/yoga.jpg'),
    "zebra":require('./quickdraw/zebra.jpg'),
    "zigzag":require('./quickdraw/zigzag.jpg'),   
}