export default images={
    "apple":require('./apple.png'),
    "ball":require('./ball.png'),
    "cat":require('./cat.png'),
    "dog":require('./dog.png'),
    "elephant":require('./elephant.png'),
    "fish":require('./fish.png'),
    "goat":require('./goat.png'),
    "hat":require('./hat.png'),
    "igloo":require('./igloo.png'),
    "jug":require('./jug.png'),
    "kite":require('./kite.png'),
    "lion":require('./lion.png'),
    "monkey":require('./monkey.png'),
    "nest":require('./nest.png'),
    "parrot":require('./parrot.png'),
    "queen":require('./queen.png'),
    "rabbit":require('./rabbit.png'),
    "sun":require("./sun.png"),
    "tiger":require("./tiger.png"),
    "umbrella":require('./umbrella.png'),
    "van":require('./van.png'),
    "wheel":require("./wheel.png"),
    "xmas tree":require("./xmastree.png"),
    "yak":require("./yak.png"),
    "zebra":require("./zebra.png")
}